### ISSUE TITLE
Create a page "thanks for downloading"

### ISSUE THREAD

**Issue by LFeh** [LFeh/css-components#26]
Inspired in @bernarddeluna [issue for the SennaJs](https://github.com/eduardolundgren/senna/issues/32)

**Comment by Jhoow13** [comment]
does this really need to be a new page ? I suggest using one of the components to do this, maybe a modal could solve the problem.

**Comment by LFeh** [comment]
It's true. But... it is an older issue. I'll closed it.

Thanks!
